<<<<<<< HEAD
##The website title
name: dev.bts.works
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: rouge


## Setup
title: BitShares 

##url: https://cedar-book.github.io/core.dev/

##url:  https://github.com/cedar-book/core.dev/
##baseurl: /cedar-book.github.io/core.dev/
##relative permalink: true;


##define base_url for valid usage in sitemap.xml and robots.txt
##base_url: https://github.com/cedar-book/core.dev

theme: jekyll-theme-slate

##plugins:
 ## - jekyll-sitemap
  
##The website description (to be used in meta tags)
description: BitShares Developers Documentation Portal
##Some frequently used keywords on your website
keywords: some, relevant, keywords, for, usage, in metatags

defaults:
  - 
    scope:
      path: "/core/intro/bitshares_core_gitflow.md"
    values:
      permalink: "/core/intro/bitshares_core_gitflow.html"
      
=======
theme: jekyll-theme-architect
>>>>>>> 988a021e8be5cb6f5778b1c1d62b1b80ea0bab5c
